apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-b
  template:
    metadata:
      labels:
        app: svc-b
    spec:
      containers:
      - name: svc-b
        image: "nggarciag/workshop:latest"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
