# # #argo-notifications-cm.yaml

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: argocd-notifications-cm
#   namespace: argocd
# data:
#   context: |
#     argocdUrl: https://localhost:8080
#   service.webhook.github-dispatch: |
#     url: https://api.github.com
#     headers:
#     - name: Authorization
#       value: Bearer $github-token
#     - name: Accept
#       value: application/vnd.github+json
#     - name: X-GitHub-Api-Version
#       value: 2022-11-28
#     - name: Content-Type
#       value: application/json
#   template.dispatch-repo-event: |
#     webhook:
#       github-dispatch:
#         method: POST
#         path: /repos/NeferGarciaG/trigger-repo/dispatches
#         body: |
#           {{- $payload := dict "event_type" "argo_deploy" "client_payload" (dict
#                 "app" .app.metadata.name
#                 "env" (index .app.metadata.labels "env")
#                 "revision" .app.status.sync.revision
#                 "health" .app.status.health.status
#                 "argo_link" (printf "%s/applications/%s/%s" .context.argocdUrl .app.metadata.namespace .app.metadata.name)
#           ) -}}
#           {{ toJson $payload }}
#   trigger.on-deployed-dispatch: |
#     - when: app.status.operationState != nil
#             && app.status.operationState.phase == 'Succeeded'
#             && app.status.health.status == 'Healthy'
#       oncePer: app.status.sync.revision
#       send: [dispatch-repo-event]

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  context: |
    argocdUrl: https://localhost:8080

  # Servicio webhook "github-dispatch"
  service.webhook.github-dispatch: |
    url: https://api.github.com
    headers:
    - name: Authorization
      value: Bearer $github-token
    - name: Accept
      value: application/vnd.github+json
    - name: X-GitHub-Api-Version
      value: 2022-11-28
    - name: Content-Type
      value: application/json

  # Mensaje (plantilla) que arma el payload y el path usando anotaciones obligatorias
  template.dispatch-repo-event: |
    {{- $owner := required "missing annotation: notify.github.owner" (index .app.metadata.annotations "notify.github.owner") -}}
    {{- $repo  := required "missing annotation: notify.github.repo"  (index .app.metadata.annotations "notify.github.repo")  -}}
    {{- $etype := (or (index .app.metadata.annotations "notify.github.event_type") "argo_deploy") -}}

    webhook:
      github-dispatch:
        method: POST
        path: /repos/{{$owner}}/{{$repo}}/dispatches
        body: |
          {{- $payload := dict "event_type" $etype "client_payload" (dict
                "app" .app.metadata.name
                "env" (index .app.metadata.labels "env")
                "revision" .app.status.sync.revision
                "health" .app.status.health.status
                "argo_link" (printf "%s/applications/%s/%s" .context.argocdUrl .app.metadata.namespace .app.metadata.name)
          ) -}}
          {{ toJson $payload }}

  # Trigger robusto: Synced + Healthy; una vez por cada revision para evitar duplicados
  trigger.on-deployed-dispatch: |
    - when: app.status.sync.status == 'Synced' && app.status.health.status == 'Healthy'
      oncePer: app.status.sync.revision
      send: [dispatch-repo-event]
 