# #argo-notifications-cm.yaml
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: argocd-notifications-cm
#   namespace: argocd
# data:
#   context: |
#     argocdUrl: https://localhost:8080/applications/argocd/kustom-app-dev
#   # Servicio "webhook" llamado github-dispatch
#   service.webhook.github-dispatch: |
#     url: https://api.github.com
#     headers:
#     - name: Authorization
#       value: Bearer $github-token
#     - name: Accept
#       value: application/vnd.github+json
#     - name: X-GitHub-Api-Version
#       value: 2022-11-28
#     - name: Content-Type
#       value: application/json
#   # Plantilla que usa el servicio 'github-dispatch'
#   template.dispatch-repo-event: |
#     webhook:
#       github-dispatch:
#         method: POST
#         path: /repos/NeferGarciaG/trigger-repo/dispatches
#         body: |
#           {{- $payload := dict "event_type" "argo_deploy" "client_payload" (dict
#                 "app" .app.metadata.name
#                 "env" (index .app.metadata.labels "env")
#                 "revision" .app.status.sync.revision
#                 "health" .app.status.health.status
#                 "argo_link" (printf "%s/applications/%s/%s" .context.argocdUrl .app.metadata.namespace .app.metadata.name)
#           ) -}}
#           {{ toJson $payload }}
#   # Dispara cuando está Synced + Healthy
#   trigger.on-healthy-synced: |
#     - when: app.status.sync.status == 'Synced' && app.status.health.status == 'Healthy'
#       send: [dispatch-repo-event]

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  context: |
    argocdUrl: https://localhost:8080
  service.webhook.github-dispatch: |
    url: https://api.github.com
    headers:
    - name: Authorization
      value: Bearer $github-token
    - name: Accept
      value: application/vnd.github+json
    - name: X-GitHub-Api-Version
      value: 2022-11-28
    - name: Content-Type
      value: application/json
  template.dispatch-repo-event: |
    webhook:
      github-dispatch:
        method: POST
        path: /repos/NeferGarciaG/trigger-repo/dispatches
        body: |
          {{- $payload := dict "event_type" "argo_deploy" "client_payload" (dict
                "app" .app.metadata.name
                "env" (index .app.metadata.labels "env")
                "revision" .app.status.sync.revision
                "health" .app.status.health.status
                "argo_link" (printf "%s/applications/%s/%s" .context.argocdUrl .app.metadata.namespace .app.metadata.name)
          ) -}}
          {{ toJson $payload }}
  trigger.on-healthy-synced: |
    - when: app.status.sync.status == 'Synced' && app.status.health.status == 'Healthy'
      send: [dispatch-repo-event]
